/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type AirdropInfoStruct = {
  airdropName: string;
  airdropAddress: AddressLike;
  totalAirdropAmount: BigNumberish;
  airdropAmountLeft: BigNumberish;
  claimAmount: BigNumberish;
  expirationDate: BigNumberish;
  airdropType: BigNumberish;
  uri: string;
};

export type AirdropInfoStructOutput = [
  airdropName: string,
  airdropAddress: string,
  totalAirdropAmount: bigint,
  airdropAmountLeft: bigint,
  claimAmount: bigint,
  expirationDate: bigint,
  airdropType: bigint,
  uri: string
] & {
  airdropName: string;
  airdropAddress: string;
  totalAirdropAmount: bigint;
  airdropAmountLeft: bigint;
  claimAmount: bigint;
  expirationDate: bigint;
  airdropType: bigint;
  uri: string;
};

export interface AirdropManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAdmin"
      | "allowAddress"
      | "allowAddresses"
      | "claim"
      | "deployAndAddAirdropERC1155"
      | "deployAndAddAirdropERC20"
      | "disallowAddress"
      | "disallowAddresses"
      | "getAirdropAmountLeft"
      | "getAirdropInfo"
      | "getAirdrops"
      | "getBalance"
      | "getClaimAmount"
      | "getExpirationDate"
      | "getTotalAirdropAmount"
      | "hasClaimed"
      | "hasExpired"
      | "isAdmin"
      | "isAllowed"
      | "removeAdmin"
      | "removeAirdrop"
      | "setRoot"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AirdropAdded"
      | "AirdropERC1155Deployed"
      | "AirdropERC20Deployed"
      | "AirdropRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowAddress",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowAddresses",
    values: [AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deployAndAddAirdropERC1155",
    values: [
      string,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployAndAddAirdropERC20",
    values: [string, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disallowAddress",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disallowAddresses",
    values: [AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAirdropAmountLeft",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAirdropInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAirdrops",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpirationDate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAirdropAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasExpired",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowed",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAirdrop",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoot",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployAndAddAirdropERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployAndAddAirdropERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disallowAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disallowAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAirdropAmountLeft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAirdropInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAirdrops",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpirationDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAirdropAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAllowed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRoot", data: BytesLike): Result;
}

export namespace AirdropAddedEvent {
  export type InputTuple = [airdropAddress: AddressLike];
  export type OutputTuple = [airdropAddress: string];
  export interface OutputObject {
    airdropAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AirdropERC1155DeployedEvent {
  export type InputTuple = [airdropAddress: AddressLike];
  export type OutputTuple = [airdropAddress: string];
  export interface OutputObject {
    airdropAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AirdropERC20DeployedEvent {
  export type InputTuple = [airdropAddress: AddressLike];
  export type OutputTuple = [airdropAddress: string];
  export interface OutputObject {
    airdropAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AirdropRemovedEvent {
  export type InputTuple = [airdropAddress: AddressLike];
  export type OutputTuple = [airdropAddress: string];
  export interface OutputObject {
    airdropAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AirdropManager extends BaseContract {
  connect(runner?: ContractRunner | null): AirdropManager;
  waitForDeployment(): Promise<this>;

  interface: AirdropManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAdmin: TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;

  allowAddress: TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;

  allowAddresses: TypedContractMethod<
    [airdropAddress: AddressLike, users: AddressLike[]],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<
    [
      airdropAddress: AddressLike,
      user: AddressLike,
      amount: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  deployAndAddAirdropERC1155: TypedContractMethod<
    [
      airdropName: string,
      tokenAddress: AddressLike,
      tokenId: BigNumberish,
      totalAirdropAmount: BigNumberish,
      claimAmount: BigNumberish,
      expirationDate: BigNumberish,
      mode: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  deployAndAddAirdropERC20: TypedContractMethod<
    [
      airdropName: string,
      tokenAddress: AddressLike,
      totalAirdropAmount: BigNumberish,
      claimAmount: BigNumberish,
      expirationDate: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  disallowAddress: TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;

  disallowAddresses: TypedContractMethod<
    [airdropAddress: AddressLike, users: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getAirdropAmountLeft: TypedContractMethod<
    [airdropAddress: AddressLike],
    [bigint],
    "view"
  >;

  getAirdropInfo: TypedContractMethod<
    [airdropAddress: AddressLike],
    [AirdropInfoStructOutput],
    "view"
  >;

  getAirdrops: TypedContractMethod<[], [string[]], "view">;

  getBalance: TypedContractMethod<
    [airdropAddress: AddressLike],
    [bigint],
    "view"
  >;

  getClaimAmount: TypedContractMethod<
    [airdropAddress: AddressLike],
    [bigint],
    "view"
  >;

  getExpirationDate: TypedContractMethod<
    [airdropAddress: AddressLike],
    [bigint],
    "view"
  >;

  getTotalAirdropAmount: TypedContractMethod<
    [airdropAddress: AddressLike],
    [bigint],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;

  hasExpired: TypedContractMethod<
    [airdropAddress: AddressLike],
    [boolean],
    "view"
  >;

  isAdmin: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  isAllowed: TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;

  removeAdmin: TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;

  removeAirdrop: TypedContractMethod<
    [airdropAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setRoot: TypedContractMethod<
    [airdropAddress: AddressLike, _root: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowAddress"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowAddresses"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, users: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      airdropAddress: AddressLike,
      user: AddressLike,
      amount: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployAndAddAirdropERC1155"
  ): TypedContractMethod<
    [
      airdropName: string,
      tokenAddress: AddressLike,
      tokenId: BigNumberish,
      totalAirdropAmount: BigNumberish,
      claimAmount: BigNumberish,
      expirationDate: BigNumberish,
      mode: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployAndAddAirdropERC20"
  ): TypedContractMethod<
    [
      airdropName: string,
      tokenAddress: AddressLike,
      totalAirdropAmount: BigNumberish,
      claimAmount: BigNumberish,
      expirationDate: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disallowAddress"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disallowAddresses"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, users: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAirdropAmountLeft"
  ): TypedContractMethod<[airdropAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAirdropInfo"
  ): TypedContractMethod<
    [airdropAddress: AddressLike],
    [AirdropInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAirdrops"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[airdropAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getClaimAmount"
  ): TypedContractMethod<[airdropAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExpirationDate"
  ): TypedContractMethod<[airdropAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalAirdropAmount"
  ): TypedContractMethod<[airdropAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasExpired"
  ): TypedContractMethod<[airdropAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAllowed"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeAirdrop"
  ): TypedContractMethod<[airdropAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRoot"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, _root: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AirdropAdded"
  ): TypedContractEvent<
    AirdropAddedEvent.InputTuple,
    AirdropAddedEvent.OutputTuple,
    AirdropAddedEvent.OutputObject
  >;
  getEvent(
    key: "AirdropERC1155Deployed"
  ): TypedContractEvent<
    AirdropERC1155DeployedEvent.InputTuple,
    AirdropERC1155DeployedEvent.OutputTuple,
    AirdropERC1155DeployedEvent.OutputObject
  >;
  getEvent(
    key: "AirdropERC20Deployed"
  ): TypedContractEvent<
    AirdropERC20DeployedEvent.InputTuple,
    AirdropERC20DeployedEvent.OutputTuple,
    AirdropERC20DeployedEvent.OutputObject
  >;
  getEvent(
    key: "AirdropRemoved"
  ): TypedContractEvent<
    AirdropRemovedEvent.InputTuple,
    AirdropRemovedEvent.OutputTuple,
    AirdropRemovedEvent.OutputObject
  >;

  filters: {
    "AirdropAdded(address)": TypedContractEvent<
      AirdropAddedEvent.InputTuple,
      AirdropAddedEvent.OutputTuple,
      AirdropAddedEvent.OutputObject
    >;
    AirdropAdded: TypedContractEvent<
      AirdropAddedEvent.InputTuple,
      AirdropAddedEvent.OutputTuple,
      AirdropAddedEvent.OutputObject
    >;

    "AirdropERC1155Deployed(address)": TypedContractEvent<
      AirdropERC1155DeployedEvent.InputTuple,
      AirdropERC1155DeployedEvent.OutputTuple,
      AirdropERC1155DeployedEvent.OutputObject
    >;
    AirdropERC1155Deployed: TypedContractEvent<
      AirdropERC1155DeployedEvent.InputTuple,
      AirdropERC1155DeployedEvent.OutputTuple,
      AirdropERC1155DeployedEvent.OutputObject
    >;

    "AirdropERC20Deployed(address)": TypedContractEvent<
      AirdropERC20DeployedEvent.InputTuple,
      AirdropERC20DeployedEvent.OutputTuple,
      AirdropERC20DeployedEvent.OutputObject
    >;
    AirdropERC20Deployed: TypedContractEvent<
      AirdropERC20DeployedEvent.InputTuple,
      AirdropERC20DeployedEvent.OutputTuple,
      AirdropERC20DeployedEvent.OutputObject
    >;

    "AirdropRemoved(address)": TypedContractEvent<
      AirdropRemovedEvent.InputTuple,
      AirdropRemovedEvent.OutputTuple,
      AirdropRemovedEvent.OutputObject
    >;
    AirdropRemoved: TypedContractEvent<
      AirdropRemovedEvent.InputTuple,
      AirdropRemovedEvent.OutputTuple,
      AirdropRemovedEvent.OutputObject
    >;
  };
}
