/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155 from "./ERC1155";
export type { erc1155 };
import type * as erc20 from "./ERC20";
export type { erc20 };
import type * as lib from "./Lib";
export type { lib };
import type * as tools from "./Tools";
export type { tools };
export type { AirdropManager } from "./AirdropManager";
