/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./Erc20.sol";
export { OpenAirdropERC20__factory } from "./OpenAirdropERC20__factory";
