/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./Erc20.sol";
export type { erc20Sol };
export type { OpenAirdropERC20 } from "./OpenAirdropERC20";
