/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc1155Sol from "./Erc1155.sol";
export { CustomAirdrop1155__factory } from "./CustomAirdrop1155__factory";
export { CustomAirdrop1155Merkle__factory } from "./CustomAirdrop1155Merkle__factory";
