/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155Sol from "./Erc1155.sol";
export type { erc1155Sol };
export type { CustomAirdrop1155 } from "./CustomAirdrop1155";
export type { CustomAirdrop1155Merkle } from "./CustomAirdrop1155Merkle";
