/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDeployerERC20,
  IDeployerERC20Interface,
} from "../../../../contracts/Tools/Types.sol/IDeployerERC20";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "airdropName",
        type: "string",
      },
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "totalAirdropAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "claimAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expirationDate",
        type: "uint256",
      },
    ],
    name: "deployAndAddAirdrop",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDeployerERC20__factory {
  static readonly abi = _abi;
  static createInterface(): IDeployerERC20Interface {
    return new Interface(_abi) as IDeployerERC20Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDeployerERC20 {
    return new Contract(address, _abi, runner) as unknown as IDeployerERC20;
  }
}
