/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Administrable } from "./Administrable";
export type { AirdropDeployerERC1155 } from "./AirdropDeployerERC1155";
export type { AirdropDeployerERC20 } from "./AirdropDeployerERC20";
